# Generated by Django 5.2.10 on 2026-01-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('album_type', models.CharField(choices=[('manual', 'Manual'), ('auto_date', 'Auto by Date'), ('auto_location', 'Auto by Location'), ('auto_person', 'Auto by Person')], default='manual', max_length=32)),
                ('location_text', models.CharField(blank=True, max_length=512, null=True)),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_lng', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('face_share_enabled', models.BooleanField(default=False)),
                ('face_threshold', models.FloatField(default=0.45)),
                ('face_encoding_version', models.IntegerField(default=1)),
                ('allow_fallback_auth', models.BooleanField(default=False)),
                ('fallback_pin_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('max_failed_attempts', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'albums',
            },
        ),
        migrations.CreateModel(
            name='AlbumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'album_images',
            },
        ),
    ]
