# Generated by Django 5.2.10 on 2026-01-09 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0002_initial'),
        ('images', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='person_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='users.personcluster'),
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='albumimage',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.album'),
        ),
        migrations.AddField(
            model_name='albumimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.image'),
        ),
        migrations.AddField(
            model_name='album',
            name='images',
            field=models.ManyToManyField(related_name='albums', through='albums.AlbumImage', to='images.image'),
        ),
        migrations.AddIndex(
            model_name='albumimage',
            index=models.Index(fields=['album', 'order'], name='album_image_album_i_4aa43d_idx'),
        ),
        migrations.AddIndex(
            model_name='albumimage',
            index=models.Index(fields=['added_at'], name='album_image_added_a_ade5ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='albumimage',
            unique_together={('album', 'image')},
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['user', 'album_type'], name='albums_user_id_8da1f8_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['user', 'created_at'], name='albums_user_id_77264a_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['is_auto_generated'], name='albums_is_auto_866a8f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('user', 'name')},
        ),
    ]
