# Generated by Django 5.2.10 on 2026-01-10 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('flag_type', models.CharField(choices=[('BOOLEAN', 'Boolean'), ('PERCENTAGE', 'Percentage Rollout'), ('USER_LIST', 'User Whitelist'), ('EXPERIMENT', 'A/B Test Experiment')], default='BOOLEAN', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('rollout_percentage', models.IntegerField(default=0, help_text='0-100 for percentage rollout')),
                ('environments', models.JSONField(default=list, help_text='List of environments where flag is active')),
                ('experiment_config', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(default=list, help_text='Tags for organizing flags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_flags', to=settings.AUTH_USER_MODEL)),
                ('user_whitelist', models.ManyToManyField(blank=True, related_name='whitelisted_features', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feature_flags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlagOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField()),
                ('variant', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_overrides', to=settings.AUTH_USER_MODEL)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_overrides', to='feature_flags.featureflag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feature_flag_overrides',
            },
        ),
        migrations.CreateModel(
            name='FeatureFlagUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField()),
                ('variant', models.CharField(blank=True, max_length=100)),
                ('environment', models.CharField(default='PRODUCTION', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='feature_flags.featureflag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feature_flag_usage',
            },
        ),
        migrations.AddIndex(
            model_name='featureflag',
            index=models.Index(fields=['key'], name='feature_fla_key_b4f409_idx'),
        ),
        migrations.AddIndex(
            model_name='featureflag',
            index=models.Index(fields=['is_active'], name='feature_fla_is_acti_ac02bc_idx'),
        ),
        migrations.AddIndex(
            model_name='featureflag',
            index=models.Index(fields=['created_at'], name='feature_fla_created_9e30e0_idx'),
        ),
        migrations.AddIndex(
            model_name='featureflagoverride',
            index=models.Index(fields=['user', 'flag'], name='feature_fla_user_id_7d7436_idx'),
        ),
        migrations.AddIndex(
            model_name='featureflagoverride',
            index=models.Index(fields=['expires_at'], name='feature_fla_expires_5192c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='featureflagoverride',
            unique_together={('user', 'flag')},
        ),
        migrations.AddIndex(
            model_name='featureflagusage',
            index=models.Index(fields=['flag', '-timestamp'], name='feature_fla_flag_id_9be20d_idx'),
        ),
        migrations.AddIndex(
            model_name='featureflagusage',
            index=models.Index(fields=['user', '-timestamp'], name='feature_fla_user_id_8ba1cd_idx'),
        ),
        migrations.AddIndex(
            model_name='featureflagusage',
            index=models.Index(fields=['-timestamp'], name='feature_fla_timesta_89942b_idx'),
        ),
    ]
