# Generated by Django 5.2.10 on 2026-01-10 10:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('AUTH', 'Authentication'), ('MEDIA', 'Media Management'), ('ALBUM', 'Album Management'), ('SHARE', 'Sharing'), ('SECURITY', 'Security'), ('ADMIN', 'Administration')], max_length=20)),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('REGISTER', 'User Registration'), ('EMAIL_VERIFY', 'Email Verification'), ('PASSWORD_RESET_REQUEST', 'Password Reset Request'), ('PASSWORD_RESET_COMPLETE', 'Password Reset Complete'), ('ACCOUNT_LOCKED', 'Account Locked'), ('ACCOUNT_UNLOCKED', 'Account Unlocked'), ('MEDIA_UPLOAD', 'Media Upload'), ('MEDIA_DELETE', 'Media Delete'), ('MEDIA_VIEW', 'Media View'), ('MEDIA_DOWNLOAD', 'Media Download'), ('ALBUM_CREATE', 'Album Create'), ('ALBUM_DELETE', 'Album Delete'), ('ALBUM_MEMBER_ADD', 'Album Member Add'), ('ALBUM_MEMBER_REMOVE', 'Album Member Remove'), ('ALBUM_ROLE_CHANGE', 'Album Role Change'), ('SHARE_CREATE', 'Share Create'), ('SHARE_ACCESS', 'Share Access'), ('SHARE_DELETE', 'Share Delete'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity'), ('RATE_LIMIT_HIT', 'Rate Limit Hit'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access')], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive')], default='OPEN', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('related_events', models.ManyToManyField(blank=True, to='audit.auditevent')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['user', '-timestamp'], name='audit_event_user_id_36e2e1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['category', '-timestamp'], name='audit_event_categor_17236d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['event_type', '-timestamp'], name='audit_event_event_t_7de374_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['ip_address', '-timestamp'], name='audit_event_ip_addr_c060e4_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['-timestamp'], name='audit_event_timesta_3a84f9_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['severity', '-created_at'], name='security_al_severit_1b3239_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['status', '-created_at'], name='security_al_status_38228d_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['user', '-created_at'], name='security_al_user_id_ccd3a0_idx'),
        ),
    ]
