# Generated by Django 5.2.10 on 2026-01-09 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facedetection',
            name='person_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_detections', to='users.personcluster'),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='images.folder'),
        ),
        migrations.AddField(
            model_name='folder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.folder'),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facedetection',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='images.image'),
        ),
        migrations.AddField(
            model_name='imageprocessingjob',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='images.image'),
        ),
        migrations.AddField(
            model_name='imagetag',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='images.image'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['user', 'created_at'], name='folders_user_id_9243f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('user', 'name', 'parent_folder')},
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['user', 'folder', 'created_at'], name='images_user_id_bf84a1_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['user', 'taken_at'], name='images_user_id_8c865f_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['checksum_sha256'], name='images_checksu_ba20fb_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['gps_lat', 'gps_lng'], name='images_gps_lat_7e8802_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('user', 'checksum_sha256')},
        ),
        migrations.AddIndex(
            model_name='facedetection',
            index=models.Index(fields=['image', 'face_id'], name='face_detect_image_i_9657f9_idx'),
        ),
        migrations.AddIndex(
            model_name='facedetection',
            index=models.Index(fields=['person_cluster'], name='face_detect_person__31f737_idx'),
        ),
        migrations.AddIndex(
            model_name='imageprocessingjob',
            index=models.Index(fields=['image', 'job_type'], name='image_proce_image_i_77b687_idx'),
        ),
        migrations.AddIndex(
            model_name='imageprocessingjob',
            index=models.Index(fields=['status', 'created_at'], name='image_proce_status_19b862_idx'),
        ),
        migrations.AddIndex(
            model_name='imagetag',
            index=models.Index(fields=['image', 'tag'], name='image_tags_image_i_b3f877_idx'),
        ),
        migrations.AddIndex(
            model_name='imagetag',
            index=models.Index(fields=['tag'], name='image_tags_tag_572596_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='imagetag',
            unique_together={('image', 'tag')},
        ),
    ]
