# Generated by Django 5.2.10 on 2026-01-09 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceClaimAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_type', models.CharField(choices=[('FACE_UPLOAD', 'Face Upload'), ('FACE_CAMERA', 'Face Camera'), ('VERIFY', 'Verification')], max_length=20)),
                ('success', models.BooleanField()),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('matched_face_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'face_claim_audits',
            },
        ),
        migrations.CreateModel(
            name='FaceClaimSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('face_embedding_json', models.JSONField()),
                ('verified_face_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'face_claim_sessions',
            },
        ),
        migrations.CreateModel(
            name='ShareAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('face_verified', models.BooleanField(default=False)),
                ('face_confidence', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'share_access_logs',
            },
        ),
        migrations.CreateModel(
            name='PublicShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('raw_token', models.CharField(blank=True, max_length=32, null=True)),
                ('scope', models.CharField(choices=[('view', 'View Only'), ('download', 'View and Download')], default='view', max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('revoked', models.BooleanField(default=False)),
                ('max_views', models.IntegerField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('ip_lock', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent_lock', models.CharField(blank=True, max_length=256, null=True)),
                ('require_face', models.BooleanField(default=False)),
                ('share_type', models.CharField(choices=[('PUBLIC', 'Public Link'), ('FACE_CLAIM', 'Face Verification Required')], default='PUBLIC', max_length=20)),
                ('face_claim_verified', models.BooleanField(default=False)),
                ('face_claim_embedding_json', models.JSONField(blank=True, null=True)),
                ('face_claim_attempts', models.IntegerField(default=0)),
                ('face_claim_last_attempt', models.DateTimeField(blank=True, null=True)),
                ('face_claim_lock_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='albums.album')),
            ],
            options={
                'db_table': 'public_shares',
            },
        ),
    ]
