# Generated by Django 5.2.10 on 2026-01-09 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sharing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicshare',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faceclaimsession',
            name='share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_claim_sessions', to='sharing.publicshare'),
        ),
        migrations.AddField(
            model_name='faceclaimaudit',
            name='share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_claim_audits', to='sharing.publicshare'),
        ),
        migrations.AddField(
            model_name='shareaccess',
            name='share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='sharing.publicshare'),
        ),
        migrations.AddIndex(
            model_name='publicshare',
            index=models.Index(fields=['token_hash'], name='public_shar_token_h_a3dec3_idx'),
        ),
        migrations.AddIndex(
            model_name='publicshare',
            index=models.Index(fields=['created_by', 'created_at'], name='public_shar_created_9298eb_idx'),
        ),
        migrations.AddIndex(
            model_name='publicshare',
            index=models.Index(fields=['expires_at', 'revoked'], name='public_shar_expires_10fbbd_idx'),
        ),
        migrations.AddIndex(
            model_name='faceclaimsession',
            index=models.Index(fields=['session_token'], name='face_claim__session_301654_idx'),
        ),
        migrations.AddIndex(
            model_name='faceclaimsession',
            index=models.Index(fields=['share', 'created_at'], name='face_claim__share_i_34223e_idx'),
        ),
        migrations.AddIndex(
            model_name='faceclaimsession',
            index=models.Index(fields=['expires_at'], name='face_claim__expires_dd9024_idx'),
        ),
        migrations.AddIndex(
            model_name='faceclaimaudit',
            index=models.Index(fields=['share', 'created_at'], name='face_claim__share_i_ffb83c_idx'),
        ),
        migrations.AddIndex(
            model_name='faceclaimaudit',
            index=models.Index(fields=['ip_address', 'created_at'], name='face_claim__ip_addr_1214d7_idx'),
        ),
        migrations.AddIndex(
            model_name='faceclaimaudit',
            index=models.Index(fields=['success', 'created_at'], name='face_claim__success_ed546f_idx'),
        ),
        migrations.AddIndex(
            model_name='shareaccess',
            index=models.Index(fields=['share', 'accessed_at'], name='share_acces_share_i_40365a_idx'),
        ),
        migrations.AddIndex(
            model_name='shareaccess',
            index=models.Index(fields=['ip_address', 'accessed_at'], name='share_acces_ip_addr_b20d74_idx'),
        ),
    ]
