# Generated by Django 5.2.10 on 2026-01-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicshare',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicshare',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicshare',
            name='unique_visitors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicshare',
            name='watermark_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicshare',
            name='watermark_opacity',
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name='publicshare',
            name='watermark_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
