# Generated by Django 5.2.10 on 2026-01-10 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0003_initial'),
        ('images', '0002_initial'),
        ('sharing', '0003_publicshare_last_accessed_publicshare_total_views_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(help_text="The 'on this day' date for this memory")),
                ('significance_score', models.FloatField(default=0.0, help_text='Calculated score based on engagement metrics and photo importance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_viewed', models.DateTimeField(blank=True, null=True)),
                ('engagement_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Memories',
            },
        ),
        migrations.CreateModel(
            name='MemoryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the memory')),
                ('significance_score', models.FloatField(default=0.0, help_text='Individual photo significance within this memory')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memories.memory')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.image')),
            ],
            options={
                'ordering': ['order', '-significance_score'],
            },
        ),
        migrations.AddField(
            model_name='memory',
            name='photos',
            field=models.ManyToManyField(related_name='memories', through='memories.MemoryPhoto', to='images.image'),
        ),
        migrations.CreateModel(
            name='MemoryPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_notifications', models.BooleanField(default=True)),
                ('notification_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('include_private_albums', models.BooleanField(default=False)),
                ('auto_generate_reels', models.BooleanField(default=True)),
                ('excluded_date_ranges', models.JSONField(default=list, help_text='List of date ranges to exclude from memories')),
                ('feature_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('excluded_albums', models.ManyToManyField(blank=True, related_name='excluded_from_memories', to='albums.album')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Memory Preferences',
            },
        ),
        migrations.CreateModel(
            name='FlashbackReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='reels/')),
                ('duration', models.IntegerField(default=30, help_text='Duration in seconds')),
                ('theme', models.CharField(default='classic', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if generation failed')),
                ('start_date', models.DateField(help_text='Start date of photos included in reel')),
                ('end_date', models.DateField(help_text='End date of photos included in reel')),
                ('photo_count', models.PositiveIntegerField(default=0)),
                ('photos', models.ManyToManyField(related_name='flashback_reels', to='images.image')),
                ('share_link', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashback_reel', to='sharing.publicshare')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashback_reels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='memories_fl_user_id_e0905b_idx'), models.Index(fields=['status'], name='memories_fl_status_8051ff_idx'), models.Index(fields=['start_date', 'end_date'], name='memories_fl_start_d_f9816f_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemoryEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('share', 'Share'), ('like', 'Like'), ('download', 'Download')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client information')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_engagements', to='memories.memory')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['memory', 'timestamp'], name='memories_me_memory__3fbf9d_idx'), models.Index(fields=['interaction_type'], name='memories_me_interac_8c35cb_idx'), models.Index(fields=['timestamp'], name='memories_me_timesta_b23f40_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemoryNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('notification_type', models.CharField(default='daily_memory', max_length=50)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='memories.memory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user', 'sent_at'], name='memories_me_user_id_8d9878_idx'), models.Index(fields=['memory'], name='memories_me_memory__70ca41_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='memoryphoto',
            index=models.Index(fields=['memory', 'order'], name='memories_me_memory__095ca6_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryphoto',
            index=models.Index(fields=['significance_score'], name='memories_me_signifi_bddca6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='memoryphoto',
            unique_together={('memory', 'photo')},
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', 'target_date'], name='memories_me_user_id_b3fcaf_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['significance_score'], name='memories_me_signifi_e0678e_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['created_at'], name='memories_me_created_974bbe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='memory',
            unique_together={('user', 'target_date')},
        ),
    ]
